# -------------------------------------------------------------
#   This file includes the basic configuration for the config properties
# -------------------------------------------------------------

config{
    # -------------------------------------------------------------
    #   DocType, Charset and header stuff
    # -------------------------------------------------------------
		
	doctype=html5	
 	htmlTag_setParams = class="no-js" lang="{$plugin.tx_bhsiteconf.language.languageName}" 
 	htmlTag_stdWrap.wrap (
<!--[if IE 9]><html class="no-js lt-ie10" lang="{$plugin.tx_bhsiteconf.language.languageName}" > <![endif]-->  
 		)

	xmlprologue           = none
	doctypeSwitch         = 1
	xhtml_cleaning        = none
	htmlSpecialChars      = 1
	// decomment only if different from utf-8
  // renderCharset         = utf-8

	// Clean html
	disableImgBorderAttr=1
	removeDefaultJS = external
	// Typo3 adds a lot of comments; get rid of them!
	disablePrefixComment=1

  	additionalHeaders = Content-Type:text/html;charset=utf-8
  	enableContentLengthHeader = 1
	sendCacheHeaders = 1

	//Admin Panel
	admPanel = 0

	// Remove CSS generated by _CSS_DEFAULT_STYLE configuration of extensions: 
	removeDefaultCss = 0

	//Minification 
	compressJs = 0
	compressCss = 0

	//Concatenation
	concatenateJs = 1
	concatenateCss = 1

	//Move all JS to footer for better performances
	moveJsFromHeaderToFooter =0
	inlineStyle2TempFile = 1
	prefixLocalAnchors   = all

	# -------------------------------------------------------------
	#   Languages. See constants
	# -------------------------------------------------------------
	sys_language_mode = content_fallback
	sys_language_overlay = hideNonTranslated

	//Write like this to prevent cache flooding
	linkVars =L(0-1)  

    //If no language is selected, use the default
    //defaultGetVars.L = 0


	sys_language_uid = {$plugin.tx_bhsiteconf.language.languageUid}
	language     = {$plugin.tx_bhsiteconf.language.languageName}
	locale_all     = {$plugin.tx_bhsiteconf.language.languageLocale}

	# -------------------------------------------------------------
	#   Header Comment, see constants
	# -------------------------------------------------------------
	headerComment(
	{$plugin.tx_bhsiteconf.settings.headerText}  
	)
	# -------------------------------------------------------------
	#   Indexed Search Engine
	# -------------------------------------------------------------
	//Enables cached pages to be indexed.
	index_enable = 0
	//Enables external media linked to on the pages to be indexed as well
	index_externals = 0

	# -------------------------------------------------------------
	#   protect emails from spam
	# -------------------------------------------------------------
	spamProtectEmailAddresses = 1
	spamProtectEmailAddresses_atSubst = [at]

	# -------------------------------------------------------------
	# Links & content sharing across domains
	# -------------------------------------------------------------
	typolinkEnableLinksAcrossDomains = 1
	typolinkCheckRootline = 1
	content_from_pid_allowOutsideDomain = 1

	# -------------------------------------------------------------
	#   url settings && enable realurl
	# -------------------------------------------------------------

  	absRefPrefix = {$plugin.tx_bhsiteconf.settings.absRefPrefix}
  	//decomment this only if you want to use it instead of absRefPrefix! (and comment absRefPrefix!); decomment also the line in constants.txt
	//baseURL = {$plugin.tx_bhsiteconf.extensionSetup.realurlPath}
	tx_realurl_enable = {$plugin.tx_bhsiteconf.extensionSetup.realurlEnable} 
  }